name: builder_release
on:
  push:
    branches: [ 'main' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get Version
      id: get_version
      uses: battila7/get-version-action@v2

    - run: npm install
    - run: npm rebuild
    - run: npm run-script build-html
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: 'AKIAWXY7DGWYB5GTWUX5'
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy examples to S3 bucket 
      run: aws s3 sync ./_site/ s3://s3robust-builder.toolkit.illinois.edu/content --delete --acl bucket-owner-full-control
    - name: Invalidate Cloudfront cache for 
      run: aws cloudfront create-invalidation --distribution-id	E2KH9MHUY6VQZR --paths "/*"
